### ISSUE TITLE
Cannot get Kord to start

### ISSUE THREAD

**Issue by Trufax** [bundit/kord-app#73]
Hello,

iam quite new to nodejs and all the realted stuff and i really struggle to get kord running.

I did everything according to the documentation but when i run "yarn dev" it fails with the following error:
```

XXXXX@XXXXXXX:~/kord/kord-app$ yarn dev
yarn run v1.22.11
$ node_modules/.bin/concurrently "nodemon -r dotenv/config server.js" "cd client && yarn start" "cd landing && yarn start"
$ react-scripts start
[1] /bin/sh: 1: react-scripts: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[0] [nodemon] 2.0.4
[0] [nodemon] to restart at any time, enter `rs`
[1] cd client && yarn start exited with code 127
[0] [nodemon] watching path(s): *.*
[0] [nodemon] watching extensions: js,mjs,json
[0] [nodemon] starting `node -r dotenv/config server.js`
$ npm run develop
[2] npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1629831242600-0.2675369837861312/node but npm is using /home/XXXXXX/.nvm/versions/node/v11.12.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
[2]
[2] > kord.app@0.1.0 develop /home/XXXXXXX/kord/kord-app/landing
[2] > gatsby develop -H 0.0.0.0
[2]
[2] sh: 1: gatsby: not found
[2] npm ERR! file sh
[2] npm ERR! code ELIFECYCLE
[2] npm ERR! errno ENOENT
[2] npm ERR! syscall spawn
[2] npm ERR! kord.app@0.1.0 develop: `gatsby develop -H 0.0.0.0`
[2] npm ERR! spawn ENOENT
[2] npm ERR!
[2] npm ERR! Failed at the kord.app@0.1.0 develop script.
[2] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[2]
[2] npm ERR! A complete log of this run can be found in:
[2] npm ERR!     /home/XXXXXX/.npm/_logs/2021-08-24T18_54_02_776Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[2] cd landing && yarn start exited with code 1
[0] (node:7015) ExperimentalWarning: The fs.promises API is experimental
[0] Listening on port 8888.
[0] (node:7015) UnhandledPromiseRejectionWarning: error: relation "keys" does not exist
[0]     at Connection.parseE (/home/XXXXXX/kord/kord-app/node_modules/pg/lib/connection.js:614:13)
[0]     at Connection.parseMessage (/home/XXXXXX/kord/kord-app/node_modules/pg/lib/connection.js:413:19)
[0]     at TLSSocket.<anonymous> (/home/XXXXXXX/kord/kord-app/node_modules/pg/lib/connection.js:129:22)
[0]     at TLSSocket.emit (events.js:197:13)
[0]     at addChunk (_stream_readable.js:288:12)
[0]     at readableAddChunk (_stream_readable.js:269:11)
[0]     at TLSSocket.Readable.push (_stream_readable.js:224:10)
[0]     at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:150:17)
[0] (node:7015) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[0] (node:7015) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0] Connected to DB {"now":"2021-08-24T18:54:02.834Z"}

[0] GET / 302 88 - 3.591 ms


```

Would packing the thing into a docker container be an option for your ? 

Thank you !

**Comment by bundit** [comment]
Closing this issue due to inactivity
